import path from "node:path";
import { fileURLToPath } from "node:url";

export const REPOSITORY_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const ALLOWED_REPOSITORIES = [REPOSITORY_ROOT];
export const CODEX_FALLBACK = "C:\\Users\\felil\\AppData\\Local\\OpenAI\\Codex\\bin\\a7c12ebff69fb123\\codex.exe";
export const DEFAULT_TIMEOUT_MS = 120_000;
export const MOCK_TIMEOUT_MS = 3_000;
export const MAX_TASK_LENGTH = 8_000;
export const MAX_CONTEXT_LENGTH = 1_000;
export const MAX_PROJECT_LENGTH = 120;
export const MAX_SOURCE_LENGTH = 40;
export const MAX_RESPONSE_LENGTH = 8_000;
export const MAX_STDERR_LENGTH = 16_384;
export const MAX_EVENT_COUNT = 200;
export const MAX_JSONL_LINE_LENGTH = 65_536;
export const MAX_RESULT_LENGTH = 4_000;
export const PROCESS_KILL_TIMEOUT_MS = 5_000;
export const PROCESS_SETTLE_TIMEOUT_MS = 2_000;
export const DATA_DIR = path.join(REPOSITORY_ROOT, ".ai-router-data");
export const RUNS_DIR = path.join(DATA_DIR, "runs");
export const LATEST_RUN_FILE = path.join(DATA_DIR, "latest-run.json");
export const COCKPIT_STATUS_FILE = path.join(DATA_DIR, "cockpit-status.json");
export const HISTORY_INDEX_FILE = path.join(DATA_DIR, "run-history.json");
export const ROUTER_VERSION = "0.13.0-test";
// Provider layer bounds (v0.13). Simulation only — no real external APIs.
export const MAX_PROVIDER_WORKFLOW_STEPS = 4;
export const MAX_PROVIDER_ALTERNATIVES = 3;
export const MAX_PROVIDER_SAFE_METADATA_KEYS = 8;
export const ROUTER_LOG_FILE = path.join(DATA_DIR, "router-events.jsonl");
export const MAX_LOG_BYTES = 512_000;
export const MAX_HISTORY_RUNS = 200;
export const DEFAULT_HISTORY_LIMIT = 25;
export const MAX_HISTORY_LIMIT = 100;
export const ADAPTER_STATUS_CACHE_MS = 60_000;
